name: brunei_tourism
description: Brunei Tourism
publish_to: 'none'
version: 6.4.23

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.4.5
  convex_bottom_bar: ^3.2.0
  email_validator: ^2.1.17
  firebase_analytics: ^10.1.6
  firebase_auth: ^4.3.0
  image_picker: ^0.8.7+1
  firebase_storage: ^11.1.0
  firebase_core: ^2.8.0
  # flutter_launcher_icons: ^0.12.0
  flutter:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  flutter_spinkit: ^5.1.0
  google_maps_flutter: ^2.2.5
  google_maps_flutter_web: ^0.4.0+7
  google_sign_in: ^6.0.2
  provider: ^6.0.5
  url_launcher: ^6.1.10
  flutter_launcher_icons: ^0.12.0

dev_dependencies:
  firebase_messaging: ^14.4.0
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.19
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#f5cb42"
  image: assets/images/biglogo.png
  android_12:
    image: assets/images/biglogo.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"
