name: bt
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  firebase_analytics: ^10.1.6
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  cloud_firestore: ^4.4.5
  email_validator: ^2.1.17
  provider: ^6.0.5
  flutter_spinkit: ^5.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.19

flutter_native_splash:
  color: "#f5cb42"
  image: assets/assets/Brunei.png

flutter:
  uses-material-design: true
  
  assets:
    - assets/
